### ISSUE TITLE
"No module named 'ASICamera'" is displayed.

### ISSUE THREAD

**Issue by siba86g** [AstroSoftDeveloper/ASICameraPythonDemoByAster#1]
I am Japanese and sorry for my poor English.
I want to control ZWO's ASI camera with python, but I don't know how to install ZWO's SDK.
I tried to run it with "TestCamera.py" but I get an error "ModuleNotFoundError: No module named 'ASICamera'".
I am a beginner and would like to know more about this.
Thank you in advance.

**Comment by AstroSoftDeveloper** [comment]
Hi,
Please try the other demo. I am not good at Python programming. Demo is provided by our enthusiastic users. They said that the demo has been tested. I'm not sure how the problem you encountered caused it. If possible, you can search for "Python calling C language dynamic link library" through Google, and perhaps you can find some solutions.
https://github.com/AstroSoftDeveloper 

Best Regards



Mouling Song @ZWO Software Team
Landline: +86 512 65923102
Homepage: astronomy-imaging-camera.com
User Forum: bbs.astronomy-imaging-camera.com
Facebook & Twitter: ZWO | ASIAIR | ASIStudio | ZWOASI 
 
From: siba86g
Date: 2023-05-30 17:53
To: AstroSoftDeveloper/ASICameraPythonDemoByAster
CC: Subscribed
Subject: [AstroSoftDeveloper/ASICameraPythonDemoByAster] "No module named 'ASICamera'" is displayed. (Issue #1)
I am Japanese and sorry for my poor English.
I want to control ZWO's ASI camera with python, but I don't know how to install ZWO's SDK.
I tried to run it with "TestCamera.py" but I get an error "ModuleNotFoundError: No module named 'ASICamera'".
I am a beginner and would like to know more about this.
Thank you in advance.

**Comment by AstroSoftDeveloper** [comment]
Hi,
I found there is a new project on GitHub and you can try it.
https://github.com/AlainPaillou/JETSONSKY



Mouling Song @ZWO Software Team
Landline: +86 512 65923102
Homepage: astronomy-imaging-camera.com
User Forum: bbs.astronomy-imaging-camera.com
Facebook & Twitter: ZWO | ASIAIR | ASIStudio | ZWOASI 
 
From: ***@***.***
Date: 2023-06-09 20:11
To: AstroSoftDeveloper/ASICameraPythonDemoByAster; AstroSoftDeveloper/ASICameraPythonDemoByAster
CC: Subscribed
Subject: Re: [AstroSoftDeveloper/ASICameraPythonDemoByAster] "No module named 'ASICamera'" is displayed. (Issue #1)
Hi,
Please try the other demo. I am not good at Python programming. Demo is provided by our enthusiastic users. They said that the demo has been tested. I'm not sure how the problem you encountered caused it. If possible, you can search for "Python calling C language dynamic link library" through Google, and perhaps you can find some solutions.
https://github.com/AstroSoftDeveloper 

Best Regards



Mouling Song @ZWO Software Team
Landline: +86 512 65923102
Homepage: astronomy-imaging-camera.com
User Forum: bbs.astronomy-imaging-camera.com
Facebook & Twitter: ZWO | ASIAIR | ASIStudio | ZWOASI 
 
From: siba86g
Date: 2023-05-30 17:53
To: AstroSoftDeveloper/ASICameraPythonDemoByAster
CC: Subscribed
Subject: [AstroSoftDeveloper/ASICameraPythonDemoByAster] "No module named 'ASICamera'" is displayed. (Issue #1)
I am Japanese and sorry for my poor English.
I want to control ZWO's ASI camera with python, but I don't know how to install ZWO's SDK.
I tried to run it with "TestCamera.py" but I get an error "ModuleNotFoundError: No module named 'ASICamera'".
I am a beginner and would like to know more about this.
Thank you in advance.
